services:
  - type: web
    name: my-bot
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python my_bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7600489635:AAEXc3iBM7g_O_L6_yL3h5vNN4o_BSWsLDE
      - key: OWNER_ID
        value: "6559745280"
      - key: OPENROUTER_API_KEY
        value: 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
      - key: WEBHOOK_URL
        value: https://my-bot-l8bf.onrender.com/webhook
