services:
  - type: web
    name: cindrella-bot
    runtime: python
    pythonVersion: 3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7600489635:AAEXc3iBM7g_O_L6_yL3h5vNN4o_BSWsLDE
      - key: OWNER_ID
        value: "6559745280"
      - key: OPENROUTER_API_KEY
        value: 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
