services:
  - type: web
    name: my-bot
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7604364226:AAFzrc-Vp1C9bysTTnec2YhozEO-cei_iAg
      - key: OWNER_ID
        value: "6559745280"
      - key: OPENROUTER_API_KEY
        value: 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
      - key: WEBHOOK_URL
        value: https://my-bot-l8bf.onrender.com/webhook
